import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { ManifestEntry } from './types.js';

const HOST = 'http://127.0.0.1:3000';

function getApisDir(): string {
  return path.resolve(process.cwd(), 'apis');
}

export function getUsagePath(templateId: string): string {
  return path.join(getApisDir(), `${templateId}.md`);
}

/**
 * A per-template "how to run this API from a console, without Claude Code or the
 * dashboard UI" guide. Pure function of the manifest entry (+ an optional real
 * example URL pulled from run history), so it can be regenerated at any time.
 */
export function buildUsageMarkdown(entry: ManifestEntry, exampleUrl?: string): string {
  const id = entry.templateId;
  const isAction = entry.kind === 'action-sequence';
  const fixed = entry.fixedTargetUrl;
  // The URL to show in the copy-paste example: a real one from history if we have it,
  // else the fixed target, else a placeholder built from the domain.
  const example = exampleUrl || fixed || `https://${entry.domainPattern}/`;
  const needsUrl = !isAction && !fixed;

  // The JSON body for the POST: fixed-target/action templates need no url.
  const body = needsUrl ? `{"url":"${example}"}` : '{}';

  const kindLine = isAction
    ? `Recorded **action-sequence** for \`${entry.domainPattern}\` — replays the recorded steps (click/fill/navigate) and returns \`{ completedSteps }\`.`
    : `**Extraction** template for \`${entry.domainPattern}\` — runs its script against a page and returns the scraped data in \`data\`.`;

  const urlNote = needsUrl
    ? `\nThis template needs a target URL: pass any real page URL on \`${entry.domainPattern}\` in the \`url\` field.`
    : `\nNo URL needed — this template always targets \`${fixed}\`, so the body is just \`{}\`.`;

  const watchBlock = isAction
    ? `
### Watch it run (opens a visible browser)

\`\`\`bash
curl -X POST ${HOST}/api/run/${id} \\
  -H "Content-Type: application/json" \\
  -d '{"headful":true}'
\`\`\`
`
    : '';

  const oneShot = needsUrl
    ? `node scripts/run.mjs ${id} "${example}"`
    : `node scripts/run.mjs ${id} "${fixed}"`;

  return `# API: ${id}

${kindLine}
${urlNote}

## 1. Start the server (once)

The server is the API. Start it and leave it running:

\`\`\`bash
apimemcp
\`\`\`

(from a source checkout: \`node dist/index.js\`.) It listens on \`${HOST}\` — the
same process that serves the dashboard also serves this HTTP API, so you don't need
to open the dashboard at all.

## 2. Call it from the console

**bash / macOS / Linux / Git Bash:**

\`\`\`bash
curl -X POST ${HOST}/api/run/${id} \\
  -H "Content-Type: application/json" \\
  -d '${body}'
\`\`\`

**Windows PowerShell:**

\`\`\`powershell
Invoke-RestMethod -Method Post -Uri ${HOST}/api/run/${id} \`
  -ContentType application/json -Body '${body}'
\`\`\`

Response is JSON: \`{ success, data?, error?, meta }\`.${isAction ? ' For an action-sequence, `data` is `{ completedSteps }`.' : ' `data` holds the extracted result.'}
${watchBlock}
## 3. One-shot, no server running (from a source checkout only)

\`\`\`bash
${oneShot}
\`\`\`

Spawns the server over stdio, runs once, prints the JSON, exits. Needs the repo
(the \`scripts/\` folder isn't in the npm package).

---

_Generated by APImeMCP. Regenerate all of these with \`node scripts/gen-usage.mjs\`._
`;
}

/** Best-effort: write the usage guide to apis/<id>.md. Never throws — a README is a
 *  convenience artifact, its failure must not break template registration. */
export async function writeUsageReadme(entry: ManifestEntry, exampleUrl?: string): Promise<void> {
  try {
    await fs.mkdir(getApisDir(), { recursive: true });
    await fs.writeFile(getUsagePath(entry.templateId), buildUsageMarkdown(entry, exampleUrl), 'utf8');
  } catch {
    // swallow - see doc comment
  }
}
